"""Public driver-neutral Ayyo physical-camera foundation API."""

from .adapter import PhysicalCameraLifecycleAdapter, PhysicalCameraSourceRegistry
from .errors import (
    PhysicalCameraConfigurationError,
    PhysicalCameraError,
    PhysicalCameraLifecycleError,
    PhysicalCameraValidationError,
)
from .fixtures import (
    FIXTURE_CAMERA,
    FIXTURE_PROVENANCE,
    FIXTURE_SOURCE_ID,
    PhysicalCameraFixtureBundle,
    fixture_camera_info_metadata,
    fixture_image_metadata,
    physical_camera_fixture_bundle,
)
from .models import (
    CAMERA_INFO_TOPIC,
    IMAGE_TOPIC,
    MAX_PHYSICAL_CAMERA_COUNT,
    MAX_PHYSICAL_CAMERA_DETAIL_LENGTH,
    MAX_PHYSICAL_CAMERA_IDENTIFIER_LENGTH,
    MAX_PHYSICAL_CAMERA_PENDING_PAIRS,
    MAX_PHYSICAL_CAMERA_SOURCES,
    PhysicalCameraAdmission,
    PhysicalCameraCalibration,
    PhysicalCameraCalibrationSource,
    PhysicalCameraCalibrationState,
    PhysicalCameraDiagnosticEvent,
    PhysicalCameraDiagnostics,
    PhysicalCameraImageMetadata,
    PhysicalCameraInfoMetadata,
    PhysicalCameraLifecycleState,
    PhysicalCameraSourceClassification,
    PhysicalCameraSourceManifest,
    PhysicalCameraTrustRequirement,
    physical_camera_session_id,
)

__all__ = [
    "CAMERA_INFO_TOPIC",
    "FIXTURE_CAMERA",
    "FIXTURE_PROVENANCE",
    "FIXTURE_SOURCE_ID",
    "IMAGE_TOPIC",
    "MAX_PHYSICAL_CAMERA_COUNT",
    "MAX_PHYSICAL_CAMERA_DETAIL_LENGTH",
    "MAX_PHYSICAL_CAMERA_IDENTIFIER_LENGTH",
    "MAX_PHYSICAL_CAMERA_PENDING_PAIRS",
    "MAX_PHYSICAL_CAMERA_SOURCES",
    "PhysicalCameraAdmission",
    "PhysicalCameraCalibration",
    "PhysicalCameraCalibrationSource",
    "PhysicalCameraCalibrationState",
    "PhysicalCameraConfigurationError",
    "PhysicalCameraDiagnosticEvent",
    "PhysicalCameraDiagnostics",
    "PhysicalCameraError",
    "PhysicalCameraFixtureBundle",
    "PhysicalCameraImageMetadata",
    "PhysicalCameraInfoMetadata",
    "PhysicalCameraLifecycleAdapter",
    "PhysicalCameraLifecycleError",
    "PhysicalCameraLifecycleState",
    "PhysicalCameraSourceClassification",
    "PhysicalCameraSourceManifest",
    "PhysicalCameraSourceRegistry",
    "PhysicalCameraTrustRequirement",
    "PhysicalCameraValidationError",
    "fixture_camera_info_metadata",
    "fixture_image_metadata",
    "physical_camera_fixture_bundle",
    "physical_camera_session_id",
]
