"""Public API for bounded deterministic Teach Mode demonstration evidence."""

from .capture import DemonstrationCaptureSession, DemonstrationRecorder
from .errors import (
    DemonstrationIntegrityError,
    DemonstrationSessionError,
    DemonstrationValidationError,
    ScenarioDemonstrationAdapterError,
    TeachModeError,
)
from .models import (
    AYYO_ROBOT_ID,
    CAPTURE_POLICY_ID,
    CAPTURE_POLICY_VERSION,
    MAX_ANNOTATIONS_PER_EPISODE,
    MAX_ANNOTATIONS_PER_EVENT,
    MAX_ANNOTATION_TEXT_LENGTH,
    MAX_EVENTS_PER_EPISODE,
    MAX_IDENTIFIER_LENGTH,
    MAX_OUTCOME_REASONS,
    MAX_REFERENCES_PER_EVENT,
    MAX_SERIALIZED_EPISODE_BYTES,
    MAX_SOURCE_TIME_NS,
    TEACH_MODE_SCHEMA_ID,
    TEACH_MODE_SCHEMA_VERSION,
    DemonstrationActionAuthority,
    DemonstrationActionDisposition,
    DemonstrationActionKind,
    DemonstrationActionReference,
    DemonstrationActionUnit,
    DemonstrationAnnotation,
    DemonstrationAnnotationKind,
    DemonstrationCapturePolicy,
    DemonstrationCaptureResult,
    DemonstrationCaptureStatus,
    DemonstrationClockKind,
    DemonstrationEpisode,
    DemonstrationEvent,
    DemonstrationEventType,
    DemonstrationObservationReference,
    DemonstrationOutcome,
    DemonstrationOutcomeStatus,
    DemonstrationProvenance,
    DemonstrationSourceKind,
    DemonstrationSourceTimeRange,
    ObservationReferenceKind,
    ReferenceEvidenceStatus,
)
from .scenario_adapter import capture_development_scenario_report
from .serialization import canonical_episode_json, episode_from_canonical_json
from .verification import (
    DemonstrationIntegrityReason,
    DemonstrationIntegrityVerification,
    verify_episode,
)

__all__ = [
    'AYYO_ROBOT_ID',
    'CAPTURE_POLICY_ID',
    'CAPTURE_POLICY_VERSION',
    'MAX_ANNOTATIONS_PER_EPISODE',
    'MAX_ANNOTATIONS_PER_EVENT',
    'MAX_ANNOTATION_TEXT_LENGTH',
    'MAX_EVENTS_PER_EPISODE',
    'MAX_IDENTIFIER_LENGTH',
    'MAX_OUTCOME_REASONS',
    'MAX_REFERENCES_PER_EVENT',
    'MAX_SERIALIZED_EPISODE_BYTES',
    'MAX_SOURCE_TIME_NS',
    'TEACH_MODE_SCHEMA_ID',
    'TEACH_MODE_SCHEMA_VERSION',
    'DemonstrationActionAuthority',
    'DemonstrationActionDisposition',
    'DemonstrationActionKind',
    'DemonstrationActionReference',
    'DemonstrationActionUnit',
    'DemonstrationAnnotation',
    'DemonstrationAnnotationKind',
    'DemonstrationCapturePolicy',
    'DemonstrationCaptureResult',
    'DemonstrationCaptureSession',
    'DemonstrationCaptureStatus',
    'DemonstrationClockKind',
    'DemonstrationEpisode',
    'DemonstrationEvent',
    'DemonstrationEventType',
    'DemonstrationIntegrityError',
    'DemonstrationIntegrityReason',
    'DemonstrationIntegrityVerification',
    'DemonstrationObservationReference',
    'DemonstrationOutcome',
    'DemonstrationOutcomeStatus',
    'DemonstrationProvenance',
    'DemonstrationRecorder',
    'DemonstrationSessionError',
    'DemonstrationSourceKind',
    'DemonstrationSourceTimeRange',
    'DemonstrationValidationError',
    'ObservationReferenceKind',
    'ReferenceEvidenceStatus',
    'ScenarioDemonstrationAdapterError',
    'TeachModeError',
    'canonical_episode_json',
    'capture_development_scenario_report',
    'episode_from_canonical_json',
    'verify_episode',
]
