"""Public deterministic Ayyo Software Showcase Foundation v1 API."""

from .canonical import (
    MAX_CAPABILITIES,
    MAX_CLASSIFICATIONS_PER_CAPABILITY,
    MAX_EVIDENCE_PER_CAPABILITY,
    MAX_EVIDENCE_REFERENCES,
    MAX_IDENTIFIER_LENGTH,
    MAX_NON_CLAIMS_PER_CAPABILITY,
    MAX_SERIALIZED_CAPABILITY_BYTES,
    MAX_SERIALIZED_CHECK_BYTES,
    MAX_SERIALIZED_EVIDENCE_BYTES,
    MAX_SERIALIZED_MANIFEST_BYTES,
    MAX_SERIALIZED_REPORT_BYTES,
)
from .catalog import (
    build_showcase_manifest,
    capability_by_id,
    verify_showcase_catalog,
)
from .errors import (
    ShowcaseCapabilityError,
    ShowcaseEvidenceError,
    ShowcaseIntegrityError,
    ShowcaseManifestError,
    ShowcaseReportError,
    SoftwareShowcaseError,
    UnknownShowcaseCapabilityError,
)
from .models import (
    SHOWCASE_MANIFEST_SCHEMA_ID,
    SHOWCASE_REPORT_SCHEMA_ID,
    SHOWCASE_SCHEMA_VERSION,
    ShowcaseCapability,
    ShowcaseCheck,
    ShowcaseCheckOutcome,
    ShowcaseClassification,
    ShowcaseEvidenceKind,
    ShowcaseEvidenceReference,
    ShowcaseManifest,
    ShowcaseNonClaim,
    ShowcaseReport,
    verify_showcase_capability,
    verify_showcase_check,
    verify_showcase_evidence,
    verify_showcase_manifest,
)
from .report import generate_showcase_report, verify_showcase_report
from .serialization import (
    ShowcaseArtifact,
    canonical_showcase_artifact_json,
    showcase_artifact_from_canonical_json,
)


__all__ = [
    "MAX_CAPABILITIES",
    "MAX_CLASSIFICATIONS_PER_CAPABILITY",
    "MAX_EVIDENCE_PER_CAPABILITY",
    "MAX_EVIDENCE_REFERENCES",
    "MAX_IDENTIFIER_LENGTH",
    "MAX_NON_CLAIMS_PER_CAPABILITY",
    "MAX_SERIALIZED_CAPABILITY_BYTES",
    "MAX_SERIALIZED_CHECK_BYTES",
    "MAX_SERIALIZED_EVIDENCE_BYTES",
    "MAX_SERIALIZED_MANIFEST_BYTES",
    "MAX_SERIALIZED_REPORT_BYTES",
    "SHOWCASE_MANIFEST_SCHEMA_ID",
    "SHOWCASE_REPORT_SCHEMA_ID",
    "SHOWCASE_SCHEMA_VERSION",
    "ShowcaseArtifact",
    "ShowcaseCapability",
    "ShowcaseCapabilityError",
    "ShowcaseCheck",
    "ShowcaseCheckOutcome",
    "ShowcaseClassification",
    "ShowcaseEvidenceError",
    "ShowcaseEvidenceKind",
    "ShowcaseEvidenceReference",
    "ShowcaseIntegrityError",
    "ShowcaseManifest",
    "ShowcaseManifestError",
    "ShowcaseNonClaim",
    "ShowcaseReport",
    "ShowcaseReportError",
    "SoftwareShowcaseError",
    "UnknownShowcaseCapabilityError",
    "build_showcase_manifest",
    "canonical_showcase_artifact_json",
    "capability_by_id",
    "generate_showcase_report",
    "showcase_artifact_from_canonical_json",
    "verify_showcase_capability",
    "verify_showcase_catalog",
    "verify_showcase_check",
    "verify_showcase_evidence",
    "verify_showcase_manifest",
    "verify_showcase_report",
]
