# Read-only fixed query for the current observed Ayyo body state.
string robot_id
---
uint8 NOT_READY=0
uint8 READY=1
uint8 UNAVAILABLE=0
uint8 PARTIAL=1
uint8 AVAILABLE=2
uint8 FRESH=1
uint8 STALE=2
uint8 FRESHNESS_UNKNOWN=0
uint8 SENSOR_UNAVAILABLE=0
uint8 SENSOR_AVAILABLE=1
uint8 SENSOR_DEGRADED=2
uint8 SENSOR_ERROR=3
uint8 SENSOR_STALE=4
uint8 status
string detail
string robot_id
string snapshot_id
string snapshot_fingerprint
uint8 availability
builtin_interfaces/Time queried_at
uint32 known_joint_count
string source_kind
string source_id
string source_clock
string source_transport
string source_interface
string[] joint_names
float64[] positions
bool[] has_velocity
float64[] velocities
bool[] has_effort
float64[] efforts
builtin_interfaces/Time[] joint_observed_at
float64[] joint_confidence
uint8[] joint_freshness
string[] joint_observation_ids
uint32 environment_entity_count
uint32 recent_evidence_count
string[] sensor_ids
string[] sensor_kinds
string[] sensor_frame_ids
uint8[] sensor_availability
bool[] has_sensor_health
uint8[] sensor_health_availability
uint8[] sensor_health_freshness
builtin_interfaces/Time[] sensor_health_observed_at
string[] sensor_health_observation_ids
string[] sensor_health_observation_fingerprints
string[] sensor_health_source_kinds
string[] sensor_health_source_ids
string[] sensor_health_source_clocks
string[] sensor_health_source_transports
string[] sensor_health_source_interfaces
string[] sensor_health_details
bool has_imu
string imu_sensor_id
string imu_frame_id
uint8 imu_availability
uint8 imu_freshness
builtin_interfaces/Time imu_observed_at
string imu_observation_id
string imu_observation_fingerprint
string imu_source_kind
string imu_source_id
string imu_source_clock
string imu_source_transport
string imu_source_interface
bool has_imu_orientation
float64[] imu_orientation_xyzw
bool has_imu_orientation_covariance
float64[] imu_orientation_covariance
bool has_imu_angular_velocity
float64[] imu_angular_velocity_xyz
bool has_imu_angular_velocity_covariance
float64[] imu_angular_velocity_covariance
bool has_imu_linear_acceleration
float64[] imu_linear_acceleration_xyz
bool has_imu_linear_acceleration_covariance
float64[] imu_linear_acceleration_covariance
bool has_imu_quality
float64 imu_quality
bool has_base_pose
string base_pose_sensor_id
uint8 base_pose_availability
uint8 base_pose_freshness
builtin_interfaces/Time base_pose_observed_at
string base_pose_source_frame_id
string base_pose_target_frame_id
float64[] base_pose_translation_xyz
float64[] base_pose_orientation_xyzw
bool has_base_pose_covariance
float64[] base_pose_covariance
string base_pose_observation_id
string base_pose_observation_fingerprint
string base_pose_source_kind
string base_pose_source_id
string base_pose_source_clock
string base_pose_source_transport
string base_pose_source_interface
bool has_base_pose_quality
float64 base_pose_quality
uint32 perception_accepted_count
uint32 perception_duplicate_count
uint32 perception_rejected_count
uint32 current_visual_count
bool has_visual_frame
string visual_sensor_id
string visual_frame_id
uint8 visual_availability
uint8 visual_freshness
builtin_interfaces/Time visual_observed_at
uint32 visual_width
uint32 visual_height
string visual_encoding
uint32 visual_step
uint64 visual_data_size_bytes
bool visual_is_bigendian
string visual_calibration_id
string visual_observation_id
string visual_observation_fingerprint
string visual_source_kind
string visual_source_id
string visual_source_clock
string visual_source_transport
string visual_source_interface
uint32 current_depth_count
bool has_depth_frame
string depth_sensor_id
string depth_frame_id
uint8 depth_availability
uint8 depth_freshness
builtin_interfaces/Time depth_observed_at
uint32 depth_width
uint32 depth_height
string depth_encoding
uint32 depth_step
uint64 depth_data_size_bytes
bool depth_is_bigendian
string depth_calibration_id
string depth_calibration_record_id
string depth_source_manifest_id
string depth_session_id
uint32 depth_valid_count
uint32 depth_invalid_count
float64 depth_minimum_m
float64 depth_maximum_m
string depth_payload_sha256
string depth_observation_id
string depth_observation_fingerprint
string depth_source_kind
string depth_source_id
string depth_source_clock
string depth_source_transport
string depth_source_interface
uint32 current_visual_interpretation_count
bool has_visual_interpretation
string visual_interpretation_sensor_id
string visual_interpretation_reference_frame_id
uint8 visual_interpretation_availability
uint8 visual_interpretation_freshness
builtin_interfaces/Time visual_interpretation_source_observed_at
builtin_interfaces/Time visual_interpretation_result_at
string visual_interpretation_observation_id
string visual_interpretation_observation_fingerprint
string visual_interpretation_source_visual_observation_id
string visual_interpretation_source_visual_fingerprint
string visual_interpretation_producer_id
string visual_interpretation_producer_kind
string visual_interpretation_model_id
string visual_interpretation_adapter_id
string visual_interpretation_interface
bool has_visual_evaluation
string visual_interpretation_producer_version
string visual_interpretation_producer_implementation_sha256
string visual_interpretation_producer_manifest_sha256
string visual_interpretation_model_version
string visual_interpretation_model_artifact_sha256
string visual_interpretation_model_format
string visual_interpretation_model_capability
string visual_interpretation_model_configuration_sha256
string visual_interpretation_model_label_schema_id
string visual_interpretation_model_label_schema_version
string visual_interpretation_model_source_classification
bool visual_interpretation_model_has_build_export_id
string visual_interpretation_model_build_export_id
string visual_interpretation_model_provenance_sha256
string visual_interpretation_dataset_id
string visual_interpretation_dataset_version
string visual_interpretation_dataset_manifest_sha256
string visual_interpretation_policy_id
string visual_interpretation_policy_version
string visual_interpretation_policy_sha256
string visual_interpretation_report_semantic_sha256
string visual_interpretation_result_schema_version
string visual_interpretation_mechanical_decision
string visual_interpretation_source_kind
string visual_interpretation_source_id
string visual_interpretation_source_clock
string visual_interpretation_source_transport
string visual_interpretation_source_interface
uint32 visual_detection_count
string[] visual_detection_ids
string[] visual_detection_categories
string[] visual_detection_labels
string[] visual_detection_coordinate_spaces
float64[] visual_detection_x_min
float64[] visual_detection_y_min
float64[] visual_detection_x_max
float64[] visual_detection_y_max
bool[] visual_detection_has_confidence
float64[] visual_detection_confidence
