"""Public API for inert authority approval and activation eligibility evidence."""

from .canonical import (
    MAX_IDENTIFIER_LENGTH,
    MAX_NOTE_LENGTH,
    MAX_SERIALIZED_APPROVAL_EVIDENCE_BYTES,
    MAX_SERIALIZED_APPROVAL_REQUEST_BYTES,
    MAX_SERIALIZED_AUTHORITY_BYTES,
    MAX_SERIALIZED_ELIGIBILITY_DECISION_BYTES,
    MAX_SERIALIZED_ELIGIBILITY_REQUEST_BYTES,
)
from .errors import (
    ActivationEligibilityDecisionError,
    ActivationEligibilityRequestError,
    ApprovalEligibilityError,
    ApprovalEligibilityIntegrityError,
    ApprovalEvidenceError,
    ApprovalRequestError,
    AuthorityReferenceError,
)
from .evaluation import (
    evaluate_activation_eligibility,
    verify_activation_eligibility_decision,
)
from .models import (
    ACTIVATION_ELIGIBILITY_DECISION_SCHEMA_ID,
    ACTIVATION_ELIGIBILITY_REQUEST_SCHEMA_ID,
    APPROVAL_ELIGIBILITY_SCHEMA_VERSION,
    APPROVAL_REQUEST_SCHEMA_ID,
    AUTHORITY_APPROVAL_EVIDENCE_SCHEMA_ID,
    AUTHORITY_REFERENCE_SCHEMA_ID,
    ActivationEligibilityDecision,
    ActivationEligibilityReason,
    ActivationEligibilityRequest,
    ActivationEligibilityStatus,
    ApprovalDisposition,
    ApprovalRequest,
    ApprovalScope,
    AuthorityApprovalEvidence,
    AuthorityReference,
    AuthorityVerificationStatus,
    verify_activation_eligibility_request,
    verify_approval_request,
    verify_authority_approval_evidence,
    verify_authority_reference,
)
from .serialization import (
    ApprovalEligibilityArtifact,
    approval_eligibility_artifact_from_canonical_json,
    canonical_approval_eligibility_artifact_json,
)


__all__ = [
    'ACTIVATION_ELIGIBILITY_DECISION_SCHEMA_ID',
    'ACTIVATION_ELIGIBILITY_REQUEST_SCHEMA_ID',
    'APPROVAL_ELIGIBILITY_SCHEMA_VERSION',
    'APPROVAL_REQUEST_SCHEMA_ID',
    'AUTHORITY_APPROVAL_EVIDENCE_SCHEMA_ID',
    'AUTHORITY_REFERENCE_SCHEMA_ID',
    'MAX_IDENTIFIER_LENGTH',
    'MAX_NOTE_LENGTH',
    'MAX_SERIALIZED_APPROVAL_EVIDENCE_BYTES',
    'MAX_SERIALIZED_APPROVAL_REQUEST_BYTES',
    'MAX_SERIALIZED_AUTHORITY_BYTES',
    'MAX_SERIALIZED_ELIGIBILITY_DECISION_BYTES',
    'MAX_SERIALIZED_ELIGIBILITY_REQUEST_BYTES',
    'ActivationEligibilityDecisionError',
    'ActivationEligibilityDecision',
    'ActivationEligibilityReason',
    'ActivationEligibilityRequestError',
    'ActivationEligibilityRequest',
    'ActivationEligibilityStatus',
    'ApprovalDisposition',
    'ApprovalEligibilityError',
    'ApprovalEligibilityArtifact',
    'ApprovalEligibilityIntegrityError',
    'ApprovalEvidenceError',
    'ApprovalRequest',
    'ApprovalRequestError',
    'ApprovalScope',
    'AuthorityApprovalEvidence',
    'AuthorityReference',
    'AuthorityReferenceError',
    'AuthorityVerificationStatus',
    'approval_eligibility_artifact_from_canonical_json',
    'canonical_approval_eligibility_artifact_json',
    'evaluate_activation_eligibility',
    'verify_activation_eligibility_decision',
    'verify_activation_eligibility_request',
    'verify_approval_request',
    'verify_authority_approval_evidence',
    'verify_authority_reference',
]
